### ISSUE TITLE
convert strings to f-strings

### ISSUE THREAD

**Issue by jessestewart1** [goatsweater/nrn-rrn#26]
f-strings are more flexible and often more concise. It would be beneficial to convert all strings using .format to f-strings.

**Comment by goatsweater** [comment]
There is a plugin for `flake8` that can help find all instances where string formatting is used, and flag anything that isn't an f-string.

I think a two-fold approach can help get this implemented with minimal disruption overall.

1. Configure an action on merge requests that will highlight when any formatting is done outside an f-string - not actually block the merge, but produce a code quality report for us to see.
2. After some break-in period, enforce the compliance to ensure no future different string formatting is used.

I've not tested it, but I know the `logging` module uses old style string replacement still (`log.info('check value of %s', some_value)`. This is a form of string formatting, but it is indirect. I don't know if it gets caught by `flake8` or if this is one of the instances you want to see converted.

**Comment by jessestewart1** [comment]
closed by https://github.com/jessestewart1/nrn-rrn/pull/25 (unable to link due to being in a different repo)
