### ISSUE TITLE
Enforce non-null geometry types on incoming data sources.

### ISSUE THREAD

**Issue by ktjaco** [goatsweater/nrn-rrn#27]
As discovered when processing Saskatchewan provincial road network data, the data pipeline currently does not handle null geometry types. 

Stage 1 currently does not note or remove null geometries prior to processing. These null geometries should be removed and noted to the incoming data provider.

**Comment by goatsweater** [comment]
One approach to finding these could be to perform some pre-flight checks. Perhaps some basic validation steps can be run against incoming data to determine if attempting to convert it has any hope of working.

I don't think too many checks will be appropriate given the variance in incoming data, but some basic questions like are there any null geometries, are they of the correct type, and so on, may provide enough of a guard against these types of problems.

**Comment by jessestewart1** [comment]
#32 and other validations will need to be put earlier in the nrn process. We've now observed that, despite having validations in stage 4, we cannot always reach these validations because of such issues.

**Comment by goatsweater** [comment]
Doing this will be made a lot easier with #10.

**Comment by jessestewart1** [comment]
None geometries now trigger an ogr error as an indirect consequence of the resolution of #35. However, proper handing of invalid geometries should still be implemented.

**Comment by jessestewart1** [comment]
I explicitly implemented a geom_type filter in stage 1 for both raw source data and recovered datasets from nrn_old. I considered only the following geometries valid: `Point`, `MultiPoint`, `LineString`, `MultiLineString`
