### ISSUE TITLE
Validation - overlapping lines

### ISSUE THREAD

**Issue by jessestewart1** [goatsweater/nrn-rrn#31]
**Is your feature request related to a problem? Please describe.**
Overlapping lines / partial-duplicates are not caught by any existing validations, except for identify_duplicate_lines which will only catch overlaps if they are duplicated in full.

**Describe the solution you'd like**
Implement validation to catch overlapping lines (multiple duplicated adjacent points)

**Comment by goatsweater** [comment]
Doing this will be made a lot easier with #10.

**Comment by jessestewart1** [comment]
Done, will be in next pull.
