### ISSUE TITLE
Validation - geometry type

### ISSUE THREAD

**Issue by jessestewart1** [goatsweater/nrn-rrn#32]
**Is your feature request related to a problem? Please describe.**
Problems have arisen from invalid and inconsistent geometry types such as mixed LineString and MultiLineString and also Nones.

**Describe the solution you'd like**
Implement a validation to ensure only LineString and Point geometries exist for spatial datasets.
LineString: roadseg, ferryseg
Point: tollpoint, blkpassage, junction

**Comment by goatsweater** [comment]
Doing this will be made a lot easier with #10.

**Comment by jessestewart1** [comment]
This may no longer be needed.
Stage 1 now both: a) explodes multi-type geometries and b) filters out geom_types not in {`Point`, `MultiPoint`, `LineString`, `MultiLineString`}. This was necessary in order for invalid data to make it to the stage 4 validations in the first place and, therefore, if the data makes it to stage 4 then these issues won't exists anyways.

**Comment by jessestewart1** [comment]
Resolved by #27
