### ISSUE TITLE
Validation - repeated adjacent points

### ISSUE THREAD

**Issue by jessestewart1** [goatsweater/nrn-rrn#33]
**Is your feature request related to a problem? Please describe.**
Many LineString geometries with repeated points have been identified from SK processing, including LineStrings which are literally just 1 pair of coordinates repeated twice.

**Describe the solution you'd like**
Implement a validation to flag LineStrings containing repeated points, where those points are adjacent in the series of coordinates. The logic will except LineStrings of > 3 points where the first and last points are identical, thereby permitting loops.

**Comment by goatsweater** [comment]
Doing this will be made a lot easier with #10.

**Comment by jessestewart1** [comment]
Done, will be in next pull.
