### ISSUE TITLE
Unable to export required file formats for Stage 5.

### ISSUE THREAD

**Issue by ktjaco** [goatsweater/nrn-rrn#35]
Stage 5 takes a long amount of time to produce the required file formats (GML, KML, GPKG, SHP) for Saskatchewan. When executing Stage 5, RAM usage was at or near 100% and was running for 12-15 hours.

**Comment by jessestewart1** [comment]
I've suggested to Shelley the removal of KML, GML, and maybe SHP, with the approval of geobase. If approved, this will no longer be an issue.

**Comment by jessestewart1** [comment]
This is resolved now due to the removal of multiprocessing support in stage 5. Will be in next pull.
