### ISSUE TITLE
Change handling of record splitting

### ISSUE THREAD

**Issue by jessestewart1** [goatsweater/nrn-rrn#42]
**Is your feature request related to a problem? Please describe.**
Currently, there exists a split_records function which will take 2 input fields and explode the dataframe records where these fields are unequal. This is not sufficient when multiple fields require splitting within the same table. This is only ever going to be an issue for strplaname where, in theory, we are supposed to receive _L and _R field matches for every address field (name, type, dir, etc.). Calling split_records for every field where there exists two matches (_L and _R) will end up duplicating the records for each of these fields, rather than just splitting the entire dataframe once based on these fields.

**Describe the solution you'd like**
- Remove all logic which handles split_records functionality.
- Implement logic to accept 1 or 2 mapped source fields to all fields in strplaname, then split the entire dataset once after field mapping occurs. The first instance of each record will keep the first specified field, the second instance will keep the second specified field, and single field specifications will duplicate the value for both record instances.

**Comment by goatsweater** [comment]
Perhaps not exactly what you are after, but the `fillna()` method can be used to coalesce across an arbitrary number of fields either forwards or backwards, effectively carrying a value across multiple columns for you. The reason I think this may be relevant is to basically just perform your field map across all the columns where differences exist, and anything left with NaN can be filled, thus duplicating the value across the fields.
