### ISSUE TITLE
Implement field mapping concatenation function

### ISSUE THREAD

**Issue by jessestewart1** [goatsweater/nrn-rrn#43]
**Is your feature request related to a problem? Please describe.**
There currently exists no field mapping function to concatenate fields.

**Describe the solution you'd like**
Implement a field mapping function to concatenate an arbitrary number of fields.

**Comment by goatsweater** [comment]
This is implemented in https://github.com/goatsweater/nrn-rrn/blob/package-cli/geobasenrn/tools.py#L47. Even accepts a join character(s).

The current implementation has a weakness in that it assumes all the columns are strings. Mixed data types would potentially cause a problem.

**Comment by jessestewart1** [comment]
Done, will be in next pull.
Handles both nans and non-string columns.
